name: Compile and Upload

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Only runs when the push contains changes to the CV itself. No need to rebuild the document if it's just misc repo files that have changed.
  #push:
    #branches: ["main"]
    #paths: ['cv/**']

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: handout.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: handout.pdf

